application: penguinsontherise
version: 1
runtime: python27
api_version: 1
threadsafe: yes


handlers:

- url: /styles
  static_dir: styles

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /content
  static_dir: content
  mime_type: application/octet-stream

- url: /mp3
  static_dir: mp3
  mime_type: audio/mpeg
  
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  static_files: index.html
  upload: index.html
  
- url: /mystaticdir/(.*\.appcache)
  static_files: mystaticdir/\1
  mime_type: text/cache-manifest
  upload: mystaticdir/(.*\.appcache)
  
error_handlers:
  - file: default_error.html

  - error_code: over_quota
    file: over_quota.html
  
libraries:
- name: webapp2
  version: "2.5.2"